### PR TITLE
Fix loadAll for composite key, fix delete condition

### PR DESCRIPTION
**Pull request by ada99**
Unfortunately full delete in detail table does not work yet.  POST does not contain any information about related table without records.

### CODE REVIEW

**Comment by mootensai** [comment]
maybe you can check on this...
```
<?php

/**
 * RelationTrait
 *
 * @author Yohanes Candrajaya <moo.tensai@gmail.com>
 * @since 1.0
 */

namespace mootensai\relation;

use Yii;
use \yii\db\ActiveRecord;
use \yii\db\Exception;
use \yii\helpers\Inflector;
use \yii\helpers\StringHelper;

trait RelationTrait {
    /*
     * 
     */

    public $oldRelationData;

    public function loadAll($POST) {

        if ($this->load($POST)) {
            $shortName = StringHelper::basename(get_class($this));
            foreach ($POST as $key => $value) {
                if ($key != $shortName && strpos($key, '_') === false) {
                    $isHasMany = is_array($value);
                    $relName = ($isHasMany) ? lcfirst($key) . 's' : lcfirst($key);
                    $rel = $this->getRelation($relName);
                    $relModelClass = $rel->modelClass;
                    $relPKAttr = $relModelClass::primaryKey();
                    if ($isHasMany) {
                        $container = [];
                        foreach ($value as $relPost) {
                            /* @var $relObj ActiveRecord */
                            $relObj = (empty($relPost[$relPKAttr[0]])) ? new $rel->modelClass : $relModelClass::findOne($relPost[$relPKAttr[0]]);
                            $relObj->load($relPost, '');
                            $container[] = $relObj;
                        }
                        $this->populateRelation($relName, $container);
                    } else {
                        $relObj = new $rel->modelClass;
                        $relObj->load($value);
                        $this->populateRelation($relName, $value);
                    }
                }
            }
            return true;
        } else {
            return false;
        }
    }

    /*
     * @param array $relations      --> alle Relationen des Modells
     */

    public function saveAll($relations) {
        /* @var $this ActiveRecord */
        $db = $this->getDb();
        $trans = $db->beginTransaction();
        try {

            /*
             * ---> Änderung WB 5.8.2015
             */
            $isNewMasterRecord = $this->isNewRecord;


            if ($this->save()) {
                if (!$isNewMasterRecord) {
                    /*
                     * <--- 
                     */
                    $error = 0;

                    /*
                     * ---> Änderung WB 5.8.2015
                     */
                    // Zunächst feststellen, welche Relationen noch weiter im Post-Array
                    // gespeichert sind, dass heisst zu diesen Relationen existieren weiterhin Datensätze
                    $thisPost = Yii::$app->request->post();

                    foreach ($thisPost as $name => $records) {
                        foreach ($relations as $key => $modelRelations) {
                            // Alle Relationen aus dem Array löschen, zu denen weiterhin Daten existieren                        
                            // Vorraussetzung: Modell mit führendem erstem Großbuchstaben 
                            //                 Relationen aus der getter-Funktionen mit nachfolgendem 's'
                            if (strcmp(ucfirst($modelRelations["name"]), $name . "s") === 0) {
                                // Ergebnis ist ein Array von Relationen, zu denen keine Daten in der Anwendung erfasst sind
                                // und deren Datensätzein der DB gelöscht werden können
                                unset($relations[$key]);
                            }
                        }
                    }

                    /*
                     * <--- 
                     */

                    foreach ($this->relatedRecords as $name => $records) {
                        $AQ = $this->getRelation($name);

                        $link = $AQ->link;
                        $notDeletedPK = [];
                        $relPKAttr = $records[0]->primaryKey();
                        $isCompositePK = (count($relPKAttr) > 1);
                        /* @var $relModel ActiveRecord */
                        foreach ($records as $index => $relModel) {
                            $notDeletedFK = [];
                            foreach ($link as $key => $value) {
                                $relModel->$key = $this->$value;
                                $notDeletedFK[$key] = "$key = '{$this->$value}'";
                            }


                            $relSave = $relModel->save();
                            if (!$relSave || !empty($relModel->errors)) {
                                $relModelWords = Inflector::camel2words(StringHelper::basename($AQ->modelClass));
                                $index++;
                                foreach ($relModel->errors as $validation) {
                                    foreach ($validation as $errorMsg) {
                                        $this->addError($name, "$relModelWords #$index : $errorMsg");
                                    }
                                }
                                $error = 1;
                            } else {
                                //GET PK OF REL MODEL
                                if ($isCompositePK) {
                                    foreach ($relModel->primaryKey as $attr => $value) {
                                        $notDeletedPK[$attr][] = "'$value'";
                                    }
                                } else {
                                    $notDeletedPK[] = "'$relModel->primaryKey'";
                                }
                            }
                        }
                        if (!$isNewMasterRecord) {
                            //DELETE WITH 'NOT IN' PK MODEL & REL MODEL
                            $notDeletedFK = implode(' AND ', $notDeletedFK);
                            if ($isCompositePK) {
                                $compiledNotDeletedPK = [];
                                foreach ($notDeletedPK as $attr => $pks) {
                                    $compiledNotDeletedPK[$attr] = "$attr NOT IN(" . implode(', ', $pks) . ")";
                                    if (!empty($compiledNotDeletedPK[$attr])) {
                                        $relModel->deleteAll("$notDeletedFK AND " . implode(' AND ', $compiledNotDeletedPK));
                                    }
                                }
                            } else {
                                $compiledNotDeletedPK = implode(',', $notDeletedPK);
                                if (!empty($compiledNotDeletedPK)) {
                                    $relModel->deleteAll($notDeletedFK . ' AND ' . $relPKAttr[0] . " NOT IN ($compiledNotDeletedPK)");
                                }
                            }
                        }
                    }
                    /*
                     * ---> Änderung WB 5.8.2015
                     */
                    // Alle Daten zu Relationen löschen, die nicht über das Post-Array aus dem Contoller übergeben werden
                    if (!$isNewMasterRecord) {

                        foreach ($relations as $key => $delRelations) {
                            $this->unlinkall($delRelations["name"], $delete = true);
                        }
                        /*
                         * <--- 
                         */
                    }

                    if ($error) {
                        $trans->rollback();
                        return false;
                    }
                    $trans->commit();
                    return true;
                } else {
                    // ein neuer Masterrecord wurde angelegt...
                    $trans->commit();
                    return TRUE;
                }
                return ;
            }
        } catch (Exception $exc) {
            $trans->rollBack();
            throw $exc;
        }
    }

//
//    /*
//     * Feststellen, ob ein Modell geändert wurde
//     */
//
//    public function checkRelatedModels() {
//
//        $changedRelModels = [];
//        foreach ($this->relatedRecords as $name => $records) {
//            foreach ($records as $index => $relModel) {
//                if (array_diff($relModel->getAttributes(), $relModel->getOldAttributes()) != NULL) {
//                    $changedRelModels[] = array('relation' => $name, 'pk' => $relModel->primaryKey);
//                }
//            }
//        }
//        return $changedRelModels;
//    }
//
//    public function searchHelper($changedRelatedRecords, $name) {
//        $index = FALSE;
//
//        foreach ($changedRelatedRecords as $data) {
//            if ($data["relation"] === $name)
//                $index = TRUE;
//        }
//
//        return $index;
//    }

    public function deleteWithRelated() {
        /* @var $this ActiveRecord */
        $db = $this->getDb();
        $trans = $db->beginTransaction();
        try {
            $error = 0;
            $relData = $this->getRelationData();
            foreach ($relData as $data) {
                if ($data['ismultiple']) {
                    $AQ = $this->getRelation($data['name']);
                    $link = $AQ->link;
                    if (count($this->{$data['name']})) {
                        $relPKAttr = $this->{$data['name']}[0]->primaryKey();
                        $isCompositePK = (count($relPKAttr) > 1);
                        foreach ($link as $key => $value) {
                            if (isset($this->$value)) {
                                $array[$key] = $key . ' = ' . $this->$value;
                            }
                        }
                        $error = !$this->{$data['name']}[0]->deleteAll(implode(' AND ', $array));
                    }
                }
            }
            if ($error) {
                $trans->rollback();
                return false;
            }
            if ($this->delete()) {
                $trans->commit();
                return true;
            }
            $trans->rollBack();
        } catch (Exception $exc) {
            $trans->rollBack();
            throw $exc;
        }
    }

    public function getRelationData() {
        $ARMethods = get_class_methods('\yii\db\ActiveRecord');
        $modelMethods = get_class_methods('\yii\base\Model');
        $reflection = new \ReflectionClass($this);
        $i = 0;
        $stack = [];
        /* @var $method \ReflectionMethod */
        foreach ($reflection->getMethods() as $method) {
            if (in_array($method->name, $ARMethods) || in_array($method->name, $modelMethods)) {
                continue;
            }
            if ($method->name === 'bindModels') {
                continue;
            }
            if ($method->name === 'attachBehaviorInternal') {
                continue;
            }
            if ($method->name === 'loadAll') {
                continue;
            }
            if ($method->name === 'saveAll') {
                continue;
            }
            if ($method->name === 'getRelationData') {
                continue;
            }
            if ($method->name === 'getAttributesWithRelatedAsPost') {
                continue;
            }
            if ($method->name === 'getAttributesWithRelated') {
                continue;
            }
            if ($method->name === 'deleteWithRelated') {
                continue;
            }
            try {
                $rel = call_user_func(array($this, $method->name));
                if ($rel instanceof \yii\db\ActiveQuery) {
                    $stack[$i]['name'] = lcfirst(str_replace('get', '', $method->name));
                    $stack[$i]['method'] = $method->name;
                    $stack[$i]['ismultiple'] = $rel->multiple;
                    $i++;
                }
            } catch (\yii\base\ErrorException $exc) {
                
            }
        }
        return $stack;
    }

    /* this function is deprecated */

    public function getAttributesWithRelatedAsPost() {
        $return = [];
        $shortName = StringHelper::basename(get_class($this));
        $return[$shortName] = $this->attributes;
        foreach ($this->relatedRecords as $records) {
            foreach ($records as $index => $record) {
                $shortNameRel = StringHelper::basename(get_class($record));
                $return[$shortNameRel][$index] = $record->attributes;
            }
        }
        return $return;
    }

    public function getAttributesWithRelated() {
        $return = $this->attributes;
        foreach ($this->relatedRecords as $name => $records) {
            foreach ($records as $index => $record) {
                $return[$name][$index] = $record->attributes;
            }
        }
        return $return;
    }

}
```

**Comment by mootensai** [comment]
credit goes to Wolfgang Bienert

**Comment by ada99** [comment]
Take a look at this
https://github.com/ada99/yii2-enhanced-gii/blob/master/crud/default/controller.php
https://github.com/ada99/yii2-relation-trait/blob/master/RelationTrait.php
Sorry I'm not making a pull request because of bad formatting on copy-paste.

**Comment by mootensai** [comment]
copy paste looks good here, maybe github already fixed that. could you make a pull request? i don't know which line you change

**Pull request closed without merging**
