### PR TITLE
Fix logic for HasOne

### PR DESCRIPTION
**Pull request by altairdeark**
We have found that logic for HasOne relations is not work, we fixed it. Could you please add this changes and update?

### CODE REVIEW

**Comment by mootensai** [comment]
I'm waiting for @markux

**Comment by mootensai** [comment]
Could you give me your sql dump to test hasOne relation?

**Comment by altairdeark** [comment]
Sorry i can not, 
just look at the code:

if ($isManyMany) {
     $container = [];
     foreach ($value as **$relPost**) {
     ...
} elseif ($isHasMany) {
             foreach ($value as **$relPost**) {
             ....
}  else {
    $relObj = (empty(**$relPost**[$relPKAttr[0]])) ? new $relModelClass :relModelClass::findOne(**$relPost**[$relPKAttr[0]]); 

??? $relPost is empty or saved from the first loop, it should be $value here
line 71

**Comment by mootensai** [comment]
@markux can you give me sql for hasOne relation?

**Comment by markux** [comment]
this is hasOne on agent table:

`CREATE TABLE `agent` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `name` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `a_user_fk` (`user_id`),
  CONSTRAINT `a_user_fk` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=latin1;`

**Comment by mootensai** [comment]
Do you use MySQL? I can't run this sql

**Comment by markux** [comment]
sorry, my export contain dot in the last row, this is correct sql:

CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

2016-05-12 10:37 GMT+02:00 Yohanes Candrajaya <notifications@github.com>:

**Comment by mootensai** [comment]
Please update, I've add hasOne problem..

**Pull request closed without merging**
