### PR TITLE
Use saveRelated() and loadRelated() 

### PR DESCRIPTION
**Pull request by thyseus**
Use saveRelated() and loadRelated() as method name as written in the documentation.

### CODE REVIEW

**Comment by mootensai** [comment]
Which one is better? saveRelated() & loadRelated() or saveAll() & loadAll() & modify the documentation?

**Comment by thyseus** [comment]
If the method saves the relations AND the data record, saveAll() would be the correct method name.
If only the related record would get saved, saveRelated() would be the correct method name.
I propose to refactor the trait to have both methods available ?

**Comment by mootensai** [comment]
the method saves the relations AND the data record. It should be named saveAll() then..

what is the use case for saveRelated() only?

**Comment by thyseus** [comment]
None. I agree to adjust the documentation !

**Pull request closed without merging**
